name: "pytest --doctest-modules"

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade PyPA packages
        run: pip install -U pip setuptools wheel

      - name: Install pipenv
        run: pip install pipenv

      - name: Install project with all dependencies
        run: pipenv install -d

      - name: Run all tests
        run: pipenv run pytest --doctest-modules
        timeout-minutes: 2
