name: pytest (Pipfile)

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.10', '3.9', '3.8', '3.7']

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove Pipfile.lock
        run: rm Pipfile.lock

      - name: Drop full Python version
        run: |
          perl -i -nwe 'print unless /^python_full_version = "[^"]+"$/' Pipfile

      - name: Substitute Python version
        run: |
          perl -i -spwe 's/^python_version = "\K[^"]+(?="$)/$pyver/' -- \
              -pyver=${{ matrix.python-version }} Pipfile

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PyPA packages
        run: python -m pip install -U pip setuptools wheel

      - name: Install pipenv
        run: pip install pipenv

      - name: Install project with all dependencies
        run: pipenv install -d

      - name: Run all tests
        run: pipenv run pytest --doctest-modules
        timeout-minutes: 2
