name: pytest (conda)

on: [push, pull_request]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.13t', '3.13', '3.12', '3.11', '3.10', '3.9', '3.8', '3.7']

      fail-fast: false

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Substitute Python version
        run: |
          perl -i -spwe 's/^ *- python=\K.+$/$pyver/' -- \
              -pyver=${{ matrix.python-version }} environment.yml

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Run all tests
        run: pytest --doctest-modules
        timeout-minutes: 2
